#!/usr/bin/env python3
"""Generate mms_visclocal_rhs.inc: the analytic RHS  f = -div( 2 k ( eps(u) - 1/3 (div u) I ) )
for the localized-feature manufactured problem of test_adaptive_visclocal_gpu.

  u(x) = sin(pi (r-R0)/(R1-R0)) * exp(-|x-c0|^2/(2 WSOL^2)) * (DX,DY,DZ)   (LOCALIZED bump at c0,
         co-located with the viscosity blob; radial sine => exactly zero on both radial boundaries)
  k(x) = KLO + (KHI-KLO) * exp( -|x-c0|^2 / (2 W^2) )                       (Gaussian blob, contrast KHI/KLO)

Emitted as CSE'd `const double tN = ...;` lines + three `data_(s,x,y,r,0/1/2) = ...` assignments, using
Kokkos:: math and cx,cy,cz in scope -- matches the mms_visckink_rhs.inc convention. All constants are
baked in (nothing runtime), so the .inc has no free parameters. Keep in sync with the C++ constants."""
import re
import sympy as sp
from sympy import symbols, sqrt, sin, exp, pi, Rational, diff, Matrix, eye, cse

cx, cy, cz = symbols("cx cy cz", real=True)

# ---- constants: MUST match test_adaptive_visclocal_gpu.cpp ----
DX, DY, DZ = 0.8451, 0.5071, 0.1690
R0, R1     = 0.5, 1.0
RB         = 0.75
C0X, C0Y, C0Z = RB * DX, RB * DY, RB * DZ
W          = 0.08   # viscosity blob width
WSOL       = 0.06   # solution bump width (feature co-located with the blob; sharper => error more localized)
KLO, KHI   = 1.0, 10.0

X = [cx, cy, cz]
r = sqrt(cx**2 + cy**2 + cz**2)

env  = sin(pi * (r - R0) / (R1 - R0))                                    # exact homogeneous Dirichlet
bump = exp(-((cx - C0X)**2 + (cy - C0Y)**2 + (cz - C0Z)**2) / (2 * WSOL**2))  # localized at c0
u    = Matrix([env * bump * DX, env * bump * DY, env * bump * DZ])

d2 = (cx - C0X)**2 + (cy - C0Y)**2 + (cz - C0Z)**2
k  = KLO + (KHI - KLO) * exp(-d2 / (2 * W**2))

# grad u : G[i,j] = d u_i / d x_j ;  eps = sym(grad u) ; div u = tr(grad u)
G     = Matrix(3, 3, lambda i, j: diff(u[i], X[j]))
eps   = (G + G.T) / 2
divu  = sum(diff(u[i], X[i]) for i in range(3))
sigma = 2 * k * (eps - Rational(1, 3) * divu * eye(3))

# f_i = -div(sigma)_i = - sum_j d sigma[i,j] / d x_j  (cse handles the common subexpressions; no simplify)
f = [-sum(diff(sigma[i, j], X[j]) for j in range(3)) for i in range(3)]

repl, reduced = cse(f, symbols=sp.numbered_symbols("t"), order="canonical")


def kokkos(s: str) -> str:
    for fn in ("sqrt", "pow", "sin", "cos", "exp", "tanh", "fabs"):
        s = re.sub(r"\b" + fn + r"\(", "Kokkos::" + fn + "(", s)
    s = s.replace("M_PI", "3.14159265358979323846")  # host-only macro -> device-safe literal
    return s


lines = []
lines.append("// AUTO-GENERATED by mms_visclocal_gen.py -- do not edit.")
lines.append("// f = -div( 2 k ( eps(u) - 1/3 (div u) I ) ), localized viscosity blob.")
lines.append("// u = sin(pi (r-R0)/(R1-R0)) * (DX,DY,DZ);  k = KLO + (KHI-KLO) exp(-|x-c0|^2/2W^2).")
for sym, expr in repl:
    lines.append(f"        const double {sym} = {kokkos(sp.ccode(expr))};")
for i in range(3):
    lines.append(f"        data_( s, x, y, r, {i} ) = {kokkos(sp.ccode(reduced[i]))};")

out = "\n".join(lines) + "\n"
with open("mms_visclocal_rhs.inc", "w") as fh:
    fh.write(out)
print(out)
print(f"// {len(repl)} CSE temporaries")
